[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit ILI9341
    earlephilhower/ESP8266Audio @ 1.9.7
    bblanchon/ArduinoJson
    madhephaestus/ESP32Servo
    arduino-libraries/ArduinoHttpClient
    vshymanskyy/TinyGSM

lib_ldf_mode = deep
extra_scripts = pre:remove_http_streams.py